import sqlite3

connect = sqlite3.connect('users.db')
# connect.execute('ALTER Table users ADD COLUMN sessionId TEXT')
# connect.execute('DROP TABLE influencers')
# connect.execute('DROP TABLE sponsors')
# connect.execute('PRAGMA foreign_keys = ON;')
cursor = connect.cursor()

# cursor.execute("SELECT * FROM users")
# cursor.execute("DROP TABLE campaigns")
cursor.execute("SELECT * FROM campaigns")
# cursor.execute("DELETE FROM campaigns")
# cursor.execute("INSERT INTO campaigns (title, description, image, niche, sponsor, budget, date) values (?, ?, ?, ?, ?, ?, ?)", ('tes', 'ta', 'im', 'ca', 'bcd', 0, 'tate'))
# connect.commit()
# connect.commit()
# cursor.execute("SELECT * FROM users")
# cursor.execute('PRAGMA foreign_keys = ON;')
# cursor.execute('DELETE FROM users WHERE username =? ', ('test',))
# cursor.execute('PRAGMA foreign_key_list(influencers);')
# cursor.execute('INSERT INTO influencers (username, presence, profic_pic, requests, total_earnings, rating) VALUES(?, ?, ?, ?, ?, ?)', ('test2', "", "", "", 0, 0))
connect.commit()
print(cursor.fetchall())